#!/bin/bash

echo "Script name: $0"
echo "First argument: $1"
echo "All arguments: $@"
echo "Number of arguments: $#"

ls /etc/passwd
echo "Exit code: $?"
# 0 (success)

ls /nonexistent
echo "Exit code: $?"
# 2 (failure)

