#!/bin/bash

# Description: Tell the color of a fruit

if [[ $# -ne 1 || $1 == "--help" ]]; then    
    echo "Usage: $0 <fruit>" >&2
    exit 1
fi

fruit="$1"

case "$fruit" in
    strawberry)
        echo "red"
        ;;
    banana)
        echo "yellow"
        ;;
    coconut)
        echo "brown"
        ;;
    *)
        echo "Unknown fruit: $fruit" >&2
        exit 1
        ;;
esac

